[package]
name = "bevy_slippy_tiles"
version = "0.5.0"
edition = "2021"
description = "Provides slippy tile fetching functionality in the Bevy game engine"
license = "MIT OR Apache-2.0"
repository = "https://github.com/edouardpoitras/bevy_slippy_tiles"

[dependencies]
bevy = "0.13"
googleprojection = "1.2"
reqwest = { version = "0.12", features = ["blocking"] }

[[example]]
name = "simple"
path = "examples/simple.rs"
