[package]
name = "bevy_slippy_tiles"
version = "0.3.5"
edition = "2021"
description = "Provides slippy tile fetching functionality in the Bevy game engine"
license = "MIT OR Apache-2.0"
repository = "https://github.com/edouardpoitras/bevy_slippy_tiles"

[dependencies]
bevy = "0.11"
futures-lite = "1.13"
googleprojection = "1.2"
reqwest = { version = "0.11", features = ["blocking"] }

[[example]]
name = "simple"
path = "examples/simple.rs"
