edition = "2021"
newline_style = "Unix"
tab_spaces = 4
match_block_trailing_comma = true
use_field_init_shorthand = true

#unstable_features = true
#imports_granularity = "Crate"
#reorder_impl_items = true
#comment_width = 120
#wrap_comments = true
#normalize_comments = true